Added the code for Energy Frequency Visualizer
Soumya-Kushwaha/SoundScape pull request #127
Opened 2024-06-15 07:29 UTC by Saksh8

2024-06-15 08:06 UTC, dinxsh approved these changes
looks good to me, should be ready for merge!

2024-06-15 08:06 UTC, dinxsh commented on Energy-Frequency-Visualizer.py
> +        fig.savefig(f'{folder}/output.png')
could you add exception handling here

2024-06-16 05:18 UTC, Soumya-Kushwaha commented on Energy-Frequency-Visualizer.py
> +        fig.savefig(f'{folder}/output.png')
@Saksh8 pls do the needful.

2024-06-16 07:13 UTC, dinxsh requested changes
minor typo changes, other than that lgtm

2024-06-16 07:13 UTC, dinxsh commented on Energy-Frequency-Visualizer.py
> +    ['Run Visualizers', ['Energy-Frequency-Visualizer', 'Waveform', 'Spectrogram', 'Intensity-vs-Frequency-and-time']],
its spectogram

2024-06-16 07:13 UTC, dinxsh commented on Energy-Frequency-Visualizer.py
> +    if event in ['Energy-Frequency-Visualizer', 'Waveform', 'Spectrogram', 'Intensity-vs-Frequency-and-time']:
spectogram not spectrogram

2024-06-16 10:42 UTC, Soumya-Kushwaha approved these changes

2024-06-16 10:42 UTC, Soumya-Kushwaha approved these changes

2024-06-16 10:47 UTC, Soumya-Kushwaha commented
Please follow the PR template. @Saksh8

2024-06-16 11:21 UTC, Saksh8 commented
> Please follow the PR template. @Saksh8

I'm unable to follow the PR template on this existing PR.

2024-06-16 12:15 UTC, Soumya-Kushwaha commented
> > Please follow the PR template. @Saksh8
> 
> I'm unable to follow the PR template on this existing PR.

Edit the first comment with basic details, plz.
Helps in tracking.

2024-06-16 17:39 UTC, dinxsh approved these changes
LGTM

2024-06-17 05:44 UTC, merged