added Depth and Perspective Visualizer
Soumya-Kushwaha/SoundScape pull request #158
Opened 2024-07-01 17:58 UTC by abckhush

Fixes: #155

2024-07-11 18:55 UTC, abckhush commented
@dinxsh Kindly review this PR. It's been a week

2024-07-11 19:51 UTC, dinxsh requested changes
lgtm. could you add a screenshot of the output. sorry for the delayed review!

2024-07-11 20:15 UTC, abckhush commented
![image](https://github.com/user-attachments/assets/561c60cf-bd12-43cc-8492-9aa6d34572da)
![image](https://github.com/user-attachments/assets/980693fe-9eae-4cc4-aa3f-4c2f3f1f5223)

2024-07-11 20:28 UTC, dinxsh approved these changes
nice, good work

2024-07-11 20:35 UTC, abckhush commented
@Soumya-Kushwaha Kindly review this.

2024-07-13 17:04 UTC, Soumya-Kushwaha approved these changes

2024-07-13 17:51 UTC, abckhush commented
Kindly merge this.

2024-07-14 21:31 UTC, dinxsh requested changes
there's a conflict now, could you check @abckhush

2024-07-15 08:27 UTC, abckhush commented
@dinx check

2024-07-16 03:21 UTC, dinxsh requested changes

2024-07-16 03:21 UTC, dinxsh commented on mainLanding.py
> +            "Spectrogram": "Spectogram.py",
Supposed to be Spectrogram.py

2024-07-16 04:29 UTC, abckhush commented
@dinxsh done.

2024-07-16 20:23 UTC, dinxsh approved these changes
good

2024-07-16 20:26 UTC, merged