Fixes issue #147
Soumya-Kushwaha/SoundScape pull request #160
Opened 2024-07-02 15:12 UTC by tkshsbcue

- Added error handling for PyAudio initialization.

-  Consolidate GUI update functions.

-  Add dynamic resizing of the graph canvas.
This is issue #147

2024-07-11 20:48 UTC, dinxsh requested changes
lgtm, could you add a screenshot of the output

2024-07-12 03:17 UTC, tkshsbcue commented
@dinxsh these where codebase related changes so refer to the code

2024-07-12 03:59 UTC, dinxsh approved these changes
alright, looks good to me. good work!

2024-07-13 17:05 UTC, Soumya-Kushwaha approved these changes

2024-07-13 17:05 UTC, merged