added workflow for autocommenting on PR Merged
Soumya-Kushwaha/SoundScape pull request #161
Opened 2024-07-07 12:41 UTC by Ratangulati

Fixes #90

2024-07-07 12:42 UTC, Ratangulati commented
@Soumya-Kushwaha I have added the workflow. Also please merge PR #131 
Thankyou

2024-07-11 20:42 UTC, dinxsh requested changes
complete these

2024-07-11 20:42 UTC, dinxsh commented on .github/workflows/autocomment_on_PR_merge.yml
> +          "body": "🎉 Your pull request has been successfully merged! 🎉 Thank you for your valuable contribution to our project. Your efforts are greatly appreciated. Feel free to reach out if you hav
add `contact mentors or soumya when needed` and mention them

2024-07-12 14:18 UTC, Ratangulati commented
<img width="855" alt="Screenshot 2024-07-12 at 7 47 49 PM" src="https://github.com/user-attachments/assets/2dd0c94e-9170-454f-ad00-a035b04ece30">

Here is the updated output.

2024-07-12 14:29 UTC, dinxsh approved these changes
lgtm. great work!

2024-07-12 15:37 UTC, Ratangulati commented
Please assign it the level and check my another PR #131

2024-07-13 17:02 UTC, Soumya-Kushwaha approved these changes

2024-07-13 17:03 UTC, merged