Added power-spectral-density curve
Soumya-Kushwaha/SoundScape pull request #170
Opened 2024-07-16 18:23 UTC by PDBharadwaj

Added power-spectral-density graph. It shows how the power of a signal is distributed across different frequency components. This helps in understanding the frequency content of the signal, identifying dominant frequencies, and analyzing harmonic structures.

https://github.com/user-attachments/assets/8f646ecd-d307-4cef-a141-612860c575f0

@dinxsh @Soumya-Kushwaha Please review and merge my PR.

2024-07-16 21:36 UTC, dinxsh requested changes
good job, add it in the main file so users can access it through the home page as well

2024-07-17 08:30 UTC, PDBharadwaj commented
> good job, add it in the main file so users can access it through the home page as well

@dinxsh @Soumya-Kushwaha updated home.py file to show PSD graph in the menu. Please review and merge the PR.

2024-07-17 08:43 UTC, dinxsh approved these changes
good job!

2024-07-26 20:17 UTC, jessicachawla approved these changes

2024-07-26 20:39 UTC, merged